services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env

  vulnerability-app:
    build:
      context: .  
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"  
    depends_on:
      - mongo
      - mongo-express
    env_file:
      - .env

volumes:
  mongo-data:

  
